### PR TITLE
Support for Laravel 7

### PR DESCRIPTION
**Pull request by leemcd56**
- Bump supported version of Laravel to `~7.0`

### CODE REVIEW

**Comment by drakakisgeo** [comment]
ru sure @leemcd56  this is the only update needed?

**Comment by leemcd56** [comment]
I didn't run into any issues, but that's not to say there may not be any!

**Comment by drakakisgeo** [comment]
Strange. I get "laravel/framework v7.0.1 requires symfony/process ^5.0 " and after some digging I also see that in https://packagist.org/packages/hmaus/drafter-php that -> symfony/process: ^2.7|^3.1.4|^4

**Comment by leemcd56** [comment]
Ah yeah, definitely need to open a PR with hendrikmaus/drafter-php to get that fixed.

**Comment by leemcd56** [comment]
@M165437 @drakakisgeo The PR for drafter-php has been merged so there should be no remaining conflicts :)

**Comment by leemcd56** [comment]
@M165437 Big _oops_ on my part. Forgot to bump `hmaus/drafter-php` to `^6.0`...

**Comment by M165437** [comment]
Yea, I just found this issue too :-) I'm on it.

**Comment by M165437** [comment]
Just released 0.9.1 with fixed dependency

**Comment by drakakisgeo** [comment]
Great work guys!

**Comment by M165437** [comment]
This still doesn't work for me. I opened another PR on `hmaus/drafter-php` to fix an incompatibility with its code and v5 of `symfony/process`. https://github.com/hendrikmaus/drafter-php/pull/13

**Comment by M165437** [comment]
PR got merged. Run `composer update` to fix this issue.

**Pull request merged**
